In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("potential-talents - Aspiring human resources - seeking human resources.csv")

In [3]:
data.shape

(104, 5)

In [4]:
data.head()

id                                          job_title  \
0   1  2019 C.T. Bauer College of Business Graduate (...   
1   2  Native English Teacher at EPIK (English Progra...   
2   3              Aspiring Human Resources Professional   
3   4             People Development Coordinator at Ryan   
4   5    Advisory Board Member at Celal Bayar University   

                              location connection  fit  
0                       Houston, Texas         85  NaN  
1                               Kanada      500+   NaN  
2  Raleigh-Durham, North Carolina Area         44  NaN  
3                        Denton, Texas      500+   NaN  
4                       İzmir, Türkiye      500+   NaN

In [5]:
data.describe()

id  fit
count  104.000000  0.0
mean    52.500000  NaN
std     30.166206  NaN
min      1.000000  NaN
25%     26.750000  NaN
50%     52.500000  NaN
75%     78.250000  NaN
max    104.000000  NaN

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id          104 non-null    int64  
 1   job_title   104 non-null    object 
 2   location    104 non-null    object 
 3   connection  104 non-null    object 
 4   fit         0 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.2+ KB


In [7]:
#replacing '500+ ' with 500
data.connection.replace({'500+ ':500}, inplace=True)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

In [9]:
tfidf_jobtitle_matrix = tfidf.fit_transform((data['job_title']))

In [11]:
search_keyword = input("Enter job keywords: ")

Enter job keywords: Aspiring human resources


In [12]:
keyword_list = [search_keyword]
user_keyword = pd.DataFrame(keyword_list, columns = ['job_keyword'])

In [13]:
user_keyword.head()

job_keyword
0  Aspiring human resources

In [14]:
user_keyword_tfidf = tfidf.transform(user_keyword['job_keyword'])

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
cos_similarity_tfidf = map(lambda x: cosine_similarity(user_keyword_tfidf, x), tfidf_jobtitle_matrix)
#result = list(cos_similarity_tfidf)

In [16]:
type(cos_similarity_tfidf)

map

In [17]:
result = list(cos_similarity_tfidf)

In [131]:
result

[array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[0.4361722]]),
 array([[0.]]),
 array([[0.4361722]]),
 array([[0.21138856]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.19430422]]),
 array([[0.28375909]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[0.4361722]]),
 array([[0.]]),
 array([[0.39564317]]),
 array([[0.2878165]]),
 array([[0.39564317]]),
 array([[0.2878165]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[0.4361722]]),
 array([[0.]]),
 array([[0.4361722]]),
 array([[0.21138856]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.19430422]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[

In [18]:
result[0][0][0]

0.28375909395128085

In [19]:
result[2][0][0]

0.7535909978974564

In [20]:
for i in range(len(result)):
    data['fit'][i] = result[i][0][0]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [21]:
#data.drop(columns='result', inplace=True)

In [22]:
#data.head()

In [23]:
data.loc[data['fit'] >= 0.4].sort_values(by = 'fit', ascending=False)

id                                          job_title  \
2    3              Aspiring Human Resources Professional   
20  21              Aspiring Human Resources Professional   
57  58              Aspiring Human Resources Professional   
45  46              Aspiring Human Resources Professional   
32  33              Aspiring Human Resources Professional   
96  97              Aspiring Human Resources Professional   
16  17              Aspiring Human Resources Professional   
23  24                Aspiring Human Resources Specialist   
35  36                Aspiring Human Resources Specialist   
5    6                Aspiring Human Resources Specialist   
48  49                Aspiring Human Resources Specialist   
59  60                Aspiring Human Resources Specialist   
72  73  Aspiring Human Resources Manager, seeking inte...   
73  74                       Human Resources Professional   
24  25  Student at Humber College and Aspiring Human R...   
38  39  Student at Humber College and Aspiring Human R...   
8    9  Student at Humber College and Aspiring Human R...   
49  50  Student at Humber College and Aspiring Human R...   
51  52  Student at Humber College and Aspiring Human R...   
6    7  Student at Humber College and Aspiring Human R...   
36  37  Student at Humber College and Aspiring Human R...   

                               location connection       fit  
2   Raleigh-Durham, North Carolina Area         44  0.753591  
20  Raleigh-Durham, North Carolina Area         44  0.753591  
57  Raleigh-Durham, North Carolina Area         44  0.753591  
45  Raleigh-Durham, North Carolina Area         44  0.753591  
32  Raleigh-Durham, North Carolina Area         44  0.753591  
96                 Kokomo, Indiana Area         71  0.753591  
16  Raleigh-Durham, North Carolina Area         44  0.753591  
23           Greater New York City Area          1  0.695679  
35           Greater New York City Area          1  0.695679  
5            Greater New York City Area          1  0.695679  
48           Greater New York City Area          1  0.695679  
59           Greater New York City Area          1  0.695679  
72                  Houston, Texas Area          7  0.576794  
73                  Greater Boston Area         16  0.460159  
24                               Kanada         61  0.436172  
38                               Kanada         61  0.436172  
8                                Kanada         61  0.436172  
49                               Kanada         61  0.436172  
51                               Kanada         61  0.436172  
6                                Kanada         61  0.436172  
36                               Kanada         61  0.436172

In [1]:
#convert job_title to tf-idf, location to tf-idf and connection 500+ with 500

In [24]:
data.head()

id                                          job_title  \
0   1  2019 C.T. Bauer College of Business Graduate (...   
1   2  Native English Teacher at EPIK (English Progra...   
2   3              Aspiring Human Resources Professional   
3   4             People Development Coordinator at Ryan   
4   5    Advisory Board Member at Celal Bayar University   

                              location connection       fit  
0                       Houston, Texas         85  0.283759  
1                               Kanada        500  0.000000  
2  Raleigh-Durham, North Carolina Area         44  0.753591  
3                        Denton, Texas        500  0.000000  
4                       İzmir, Türkiye        500  0.000000

In [25]:
tfidf_jobtitle_matrix.shape

(104, 181)

In [26]:
tfidf_location_matrix = tfidf.fit_transform((data['location']))

In [27]:
tfidf_location_matrix.shape

(104, 71)

In [28]:
df_jobtitle = pd.DataFrame(tfidf_jobtitle_matrix.toarray())
df_location = pd.DataFrame(tfidf_location_matrix.toarray())

In [29]:
data_processed = pd.concat([data, df_jobtitle, df_location], axis = 1)

In [30]:
data_processed.shape

(104, 257)

In [31]:
data_processed.drop(['job_title', 'location'], axis=1, inplace=True)

In [32]:
data_processed.shape

(104, 255)

In [33]:
data_processed.head()

id connection       fit        0    1    2    3    4    5    6  ...   61  \
0   1         85  0.283759  0.33906  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
1   2        500  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
2   3         44  0.753591  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
3   4        500  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
4   5        500  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   

    62        63   64        65   66   67   68   69        70  
0  0.0  0.645479  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
1  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
2  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
3  0.0  0.548921  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
4  0.0  0.000000  0.0  0.707107  0.0  0.0  0.0  0.0  0.707107  

[5 rows x 255 columns]

### Word2Vec implementation

In [34]:
import numpy
import gensim

In [35]:
import gensim.downloader as api

In [38]:
# load w2v model
corpus = api.load('word2vec-google-news-300')
#word2vec_model = gensim.load("word2vec-google-news-300")

[=================================================-] 99.8% 1659.8/1662.8MB downloaded


In [39]:
def cosine_similarity(vec1, vec2):
    cosine_similarity = numpy.dot(vec1, vec2) / (numpy.linalg.norm(vec1) * numpy.linalg.norm(vec2))
    return cosine_similarity

In [62]:
search_term_embedding = []
search_word = search_keyword.split()
for term in search_word:
#    print(corpus[term])
    search_term_embedding.append(corpus[term])

In [43]:
#averaged search term embedding
search_term_embedding = numpy.mean(search_term_embedding)  

In [56]:
search_term_embedding

-0.006466749

In [77]:
import re

def remove_sym_specialchar(text):
#    pattern = r'[^a-zA-Z0-9\s]'
#    text = re.sub(pattern,'', text)
    text_nonum = re.sub(r'\d+', '', text)
    return text_nonum

In [78]:
data['job_title'] = data.job_title.apply(remove_sym_specialchar)

In [79]:
data['job_title'][0]

' CT Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional'

In [138]:
#calculate vector for the sentence by add individual word vectors using numpy.mean

jobtitle_embeddings = []
    
for text in data['job_title']:
    jobtitle_embedding = []
    for word in text.split():
        if word not in corpus:
            jobtitle_embedding.append(0)
        else:   
            jobtitle_embedding.append(corpus[word])

    jobtitle_embedding = numpy.mean(jobtitle_embedding)
#average candidate job title embedding to represent the sentence

    jobtitle_embeddings.append(jobtitle_embedding)

In [141]:
len(jobtitle_embeddings)

104

In [137]:
type(jobtitle_embedding)

numpy.float32

In [142]:
cosine_similirity_scores = []

#cos_similarity_lam = map(lambda x: cosine_similarity(search_term_embedding, x), jobtitle_embeddings)

for jobtitle_embedding in jobtitle_embeddings:
    score = cosine_similarity(search_term_embedding, jobtitle_embedding)
    cosine_similirity_scores.append(score)

In [143]:
type(cosine_similirity_scores)

list

In [144]:
len(cosine_similirity_scores)

104

In [145]:
cosine_similirity_scores[0]

array([0.2513946 , 0.09600574, 0.08090651], dtype=float32)

In [146]:
cosine_similirity_scores[1]

array([[ 3.89722511e-02, -4.77363467e-02,  3.49631440e-03,
         3.56157869e-02, -1.76214240e-02, -5.48222102e-02,
        -4.77363467e-02, -4.69904654e-02,  5.81786707e-02,
         1.92297285e-03, -5.14657497e-02, -1.73417199e-02,
        -1.18408510e-02, -2.13508271e-02,  3.74804884e-02,
        -1.26799671e-02, -5.48222102e-02, -8.24197829e-02,
         2.17237659e-02, -1.94861256e-02,  2.62922850e-02,
        -1.68755446e-02,  9.46335774e-03,  4.02775407e-02,
         6.19080737e-02,  4.77363467e-02, -1.50108431e-02,
         2.92758066e-02, -6.75021783e-02,  3.21660936e-03,
        -3.99046019e-02,  3.13269757e-02,  4.45663556e-02,
         8.68950635e-02,  3.87857817e-02, -1.92996562e-02,
        -1.40784923e-02,  2.13508271e-02, -1.79011300e-02,
         3.69210802e-02,  3.75271076e-03,  7.83174410e-02,
         8.39115493e-03,  5.71064698e-03,  1.92064196e-02,
        -2.75975764e-02,  3.37510891e-02, -7.12315738e-02,
        -9.18365270e-03, -2.55464036e-02,  1.04423255e-0