In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("potential-talents - Aspiring human resources - seeking human resources.csv")

In [3]:
data.shape

(104, 5)

In [4]:
data.head()

id                                          job_title  \
0   1  2019 C.T. Bauer College of Business Graduate (...   
1   2  Native English Teacher at EPIK (English Progra...   
2   3              Aspiring Human Resources Professional   
3   4             People Development Coordinator at Ryan   
4   5    Advisory Board Member at Celal Bayar University   

                              location connection  fit  
0                       Houston, Texas         85  NaN  
1                               Kanada      500+   NaN  
2  Raleigh-Durham, North Carolina Area         44  NaN  
3                        Denton, Texas      500+   NaN  
4                       İzmir, Türkiye      500+   NaN

In [5]:
data.describe()

id  fit
count  104.000000  0.0
mean    52.500000  NaN
std     30.166206  NaN
min      1.000000  NaN
25%     26.750000  NaN
50%     52.500000  NaN
75%     78.250000  NaN
max    104.000000  NaN

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id          104 non-null    int64  
 1   job_title   104 non-null    object 
 2   location    104 non-null    object 
 3   connection  104 non-null    object 
 4   fit         0 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.2+ KB


In [7]:
#replacing '500+ ' with 500
data.connection.replace({'500+ ':500}, inplace=True)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

In [9]:
tfidf_jobtitle_matrix = tfidf.fit_transform((data['job_title']))

In [10]:
tfidf_jobtitle_matrix.shape

(104, 181)

In [11]:
search_keyword = input("Enter job keywords: ")

Enter job keywords: Aspiring human resources


In [12]:
keyword_list = [search_keyword]
user_keyword = pd.DataFrame(keyword_list, columns = ['job_keyword'])

In [13]:
user_keyword.head()

job_keyword
0  Aspiring human resources

In [14]:
user_keyword.shape

(1, 1)

In [15]:
user_keyword_tfidf = tfidf.transform(user_keyword['job_keyword'])

In [16]:
type(user_keyword_tfidf)

scipy.sparse.csr.csr_matrix

In [17]:
user_keyword_tfidf.shape

(1, 181)

In [18]:
user_keyword_tfidf

<1x181 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
cos_similarity_tfidf = map(lambda x: cosine_similarity(user_keyword_tfidf, x), tfidf_jobtitle_matrix)
#result = list(cos_similarity_tfidf)

In [20]:
type(cos_similarity_tfidf)

map

In [21]:
result = list(cos_similarity_tfidf)

In [22]:
result

[array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[0.4361722]]),
 array([[0.]]),
 array([[0.4361722]]),
 array([[0.21138856]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.19430422]]),
 array([[0.28375909]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[0.4361722]]),
 array([[0.]]),
 array([[0.39564317]]),
 array([[0.2878165]]),
 array([[0.39564317]]),
 array([[0.2878165]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[0.4361722]]),
 array([[0.]]),
 array([[0.4361722]]),
 array([[0.21138856]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.19430422]]),
 array([[0.28375909]]),
 array([[0.]]),
 array([[0.753591]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.69567872]]),
 array([[

In [23]:
result[0][0][0]

0.28375909395128085

In [24]:
result[2][0][0]

0.7535909978974564

In [25]:
for i in range(len(result)):
    data['fit'][i] = result[i][0][0]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [26]:
#data.drop(columns='result', inplace=True)

In [27]:
#data.head()

In [28]:
data.loc[data['fit'] >= 0.4].sort_values(by = 'fit', ascending=False)

id                                          job_title  \
2    3              Aspiring Human Resources Professional   
20  21              Aspiring Human Resources Professional   
57  58              Aspiring Human Resources Professional   
45  46              Aspiring Human Resources Professional   
32  33              Aspiring Human Resources Professional   
96  97              Aspiring Human Resources Professional   
16  17              Aspiring Human Resources Professional   
23  24                Aspiring Human Resources Specialist   
35  36                Aspiring Human Resources Specialist   
5    6                Aspiring Human Resources Specialist   
48  49                Aspiring Human Resources Specialist   
59  60                Aspiring Human Resources Specialist   
72  73  Aspiring Human Resources Manager, seeking inte...   
73  74                       Human Resources Professional   
24  25  Student at Humber College and Aspiring Human R...   
38  39  Student at Humber College and Aspiring Human R...   
8    9  Student at Humber College and Aspiring Human R...   
49  50  Student at Humber College and Aspiring Human R...   
51  52  Student at Humber College and Aspiring Human R...   
6    7  Student at Humber College and Aspiring Human R...   
36  37  Student at Humber College and Aspiring Human R...   

                               location connection       fit  
2   Raleigh-Durham, North Carolina Area         44  0.753591  
20  Raleigh-Durham, North Carolina Area         44  0.753591  
57  Raleigh-Durham, North Carolina Area         44  0.753591  
45  Raleigh-Durham, North Carolina Area         44  0.753591  
32  Raleigh-Durham, North Carolina Area         44  0.753591  
96                 Kokomo, Indiana Area         71  0.753591  
16  Raleigh-Durham, North Carolina Area         44  0.753591  
23           Greater New York City Area          1  0.695679  
35           Greater New York City Area          1  0.695679  
5            Greater New York City Area          1  0.695679  
48           Greater New York City Area          1  0.695679  
59           Greater New York City Area          1  0.695679  
72                  Houston, Texas Area          7  0.576794  
73                  Greater Boston Area         16  0.460159  
24                               Kanada         61  0.436172  
38                               Kanada         61  0.436172  
8                                Kanada         61  0.436172  
49                               Kanada         61  0.436172  
51                               Kanada         61  0.436172  
6                                Kanada         61  0.436172  
36                               Kanada         61  0.436172

In [29]:
#convert job_title to tf-idf, location to tf-idf and connection 500+ with 500

In [30]:
data.head()

id                                          job_title  \
0   1  2019 C.T. Bauer College of Business Graduate (...   
1   2  Native English Teacher at EPIK (English Progra...   
2   3              Aspiring Human Resources Professional   
3   4             People Development Coordinator at Ryan   
4   5    Advisory Board Member at Celal Bayar University   

                              location connection       fit  
0                       Houston, Texas         85  0.283759  
1                               Kanada        500  0.000000  
2  Raleigh-Durham, North Carolina Area         44  0.753591  
3                        Denton, Texas        500  0.000000  
4                       İzmir, Türkiye        500  0.000000

In [31]:
tfidf_jobtitle_matrix.shape

(104, 181)

In [32]:
tfidf_location_matrix = tfidf.fit_transform((data['location']))

In [33]:
tfidf_location_matrix.shape

(104, 71)

In [34]:
df_jobtitle = pd.DataFrame(tfidf_jobtitle_matrix.toarray())
df_location = pd.DataFrame(tfidf_location_matrix.toarray())

In [35]:
data_processed = pd.concat([data, df_jobtitle, df_location], axis = 1)

In [36]:
data_processed.shape

(104, 257)

In [37]:
data_processed.drop(['job_title', 'location'], axis=1, inplace=True)

In [38]:
data_processed.shape

(104, 255)

In [39]:
data_processed.head()

id connection       fit        0    1    2    3    4    5    6  ...   61  \
0   1         85  0.283759  0.33906  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
1   2        500  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
2   3         44  0.753591  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
3   4        500  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   
4   5        500  0.000000  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0   

    62        63   64        65   66   67   68   69        70  
0  0.0  0.645479  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
1  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
2  0.0  0.000000  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
3  0.0  0.548921  0.0  0.000000  0.0  0.0  0.0  0.0  0.000000  
4  0.0  0.000000  0.0  0.707107  0.0  0.0  0.0  0.0  0.707107  

[5 rows x 255 columns]

### Word2Vec implementation

In [40]:
import numpy
import gensim

In [41]:
import gensim.downloader as api

In [42]:
# load w2v model
corpus = api.load('word2vec-google-news-300')
#word2vec_model = gensim.load("word2vec-google-news-300")

In [106]:
type(corpus)

gensim.models.keyedvectors.Word2VecKeyedVectors

In [43]:
def cosine_similarity(vec1, vec2):
    cosine_similarity = numpy.dot(vec1, vec2) / (numpy.linalg.norm(vec1) * numpy.linalg.norm(vec2))
    return cosine_similarity

In [51]:
search_term_embedding = []
for term in search_keyword.split():
    search_term_embedding.append(corpus[term])

In [53]:
len(search_term_embedding)

3

In [54]:
search_term_embedding

[array([-2.04101562e-01,  2.50000000e-01, -1.83105469e-02, -1.86523438e-01,
         9.22851562e-02,  2.87109375e-01,  2.50000000e-01,  2.46093750e-01,
        -3.04687500e-01, -1.00708008e-02,  2.69531250e-01,  9.08203125e-02,
         6.20117188e-02,  1.11816406e-01, -1.96289062e-01,  6.64062500e-02,
         2.87109375e-01,  4.31640625e-01, -1.13769531e-01,  1.02050781e-01,
        -1.37695312e-01,  8.83789062e-02, -4.95605469e-02, -2.10937500e-01,
        -3.24218750e-01, -2.50000000e-01,  7.86132812e-02, -1.53320312e-01,
         3.53515625e-01, -1.68457031e-02,  2.08984375e-01, -1.64062500e-01,
        -2.33398438e-01, -4.55078125e-01, -2.03125000e-01,  1.01074219e-01,
         7.37304688e-02, -1.11816406e-01,  9.37500000e-02, -1.93359375e-01,
        -1.96533203e-02, -4.10156250e-01, -4.39453125e-02, -2.99072266e-02,
        -1.00585938e-01,  1.44531250e-01, -1.76757812e-01,  3.73046875e-01,
         4.80957031e-02,  1.33789062e-01, -5.46875000e-01,  4.25781250e-01,
         1.7

In [64]:
search_term_embedding_mean = numpy.mean(search_term_embedding, axis=0)

In [66]:
print(search_term_embedding_mean.shape)
#search_term_embedding_mean

(300,)


In [63]:
search_term_embedding[0].shape

(300,)

In [67]:
import re

def remove_sym_specialchar(text):
#    pattern = r'[^a-zA-Z0-9\s]'
#    text = re.sub(pattern,'', text)
    text_nonum = re.sub(r'\d+', '', text)
    return text_nonum

In [68]:
data['job_title'] = data.job_title.apply(remove_sym_specialchar)

In [69]:
data['job_title'][0]

' C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional'

In [73]:
#calculate vector for the sentence by add individual word vectors using numpy.mean

jobtitle_embeddings = []
    
for text in data['job_title']:
    jobtitle_embedding = []
    for word in text.split():
        if word not in corpus:
            jobtitle_embedding.append(numpy.zeros((300)))
        else:   
            jobtitle_embedding.append(corpus[word])

    jobtitle_embedding = numpy.mean(jobtitle_embedding, axis = 0)
#average candidate job title embedding to represent the sentence

    jobtitle_embeddings.append(jobtitle_embedding)

In [94]:
len(jobtitle_embeddings)

104

In [109]:
type(jobtitle_embeddings)

list

In [98]:
jobtitle_embeddings[2].shape

(300,)

In [108]:
jobtitle_embeddings[0]

array([-0.02456229, -0.02502877,  0.0454058 , -0.01222447,  0.04069737,
        0.01130458,  0.05714634,  0.000994  , -0.04078456,  0.00482178,
        0.00513567,  0.03986795,  0.00229318,  0.05874852, -0.02300589,
        0.0027553 ,  0.06499372,  0.06651088, -0.01143973,  0.00966099,
       -0.02326093,  0.04976109, -0.04040527, -0.0322876 , -0.01926967,
        0.04178892, -0.06484549,  0.03099741,  0.05024501,  0.01559448,
       -0.00066267,  0.00816563, -0.01757812, -0.08856201, -0.00515311,
       -0.03009905,  0.0246582 ,  0.01063756, -0.03761509, -0.03062221,
       -0.01296779,  0.02180699, -0.06321934,  0.05019651, -0.06492397,
       -0.00915527, -0.02219936,  0.03797259,  0.0408674 ,  0.07159424,
       -0.11314174,  0.01199777,  0.00265939,  0.01469707,  0.03907721,
        0.01839774, -0.05896868, -0.05235509, -0.0335519 , -0.02165876,
       -0.04248047, -0.0242315 , -0.04926232,  0.00129046, -0.00273132,
       -0.01701028,  0.00744629, -0.00530515,  0.02969796,  0.03

In [76]:
cosine_similirity_scores = []

#cos_similarity_lam = map(lambda x: cosine_similarity(search_term_embedding, x), jobtitle_embeddings)

for jobtitle_embedding in jobtitle_embeddings:
    score = cosine_similarity(search_term_embedding_mean, jobtitle_embedding)
#    score = numpy.mean(score)
    cosine_similirity_scores.append(score)

In [80]:
cosine_similirity_scores[3]

0.21032198

In [81]:
cosine_similirity_scores

[0.45685704158807683,
 0.2911007259684649,
 0.6287277,
 0.21032198,
 0.14989693,
 0.598271,
 0.5338431551728507,
 0.24628457,
 0.5338431551728507,
 0.4653258503903726,
 0.21811514,
 0.24647247512062803,
 0.22101595,
 0.45685704158807683,
 0.45685704158807683,
 0.2911007259684649,
 0.6287277,
 0.21032198,
 0.45685704158807683,
 0.2911007259684649,
 0.6287277,
 0.21032198,
 0.14989693,
 0.598271,
 0.5338431551728507,
 0.24628457,
 0.57632416,
 0.45409384,
 0.57632416,
 0.45409384,
 0.45685704158807683,
 0.2911007259684649,
 0.6287277,
 0.21032198,
 0.14989693,
 0.598271,
 0.5338431551728507,
 0.24628457,
 0.5338431551728507,
 0.4653258503903726,
 0.21811514,
 0.24647247512062803,
 0.22101595,
 0.45685704158807683,
 0.2911007259684649,
 0.6287277,
 0.21032198,
 0.14989693,
 0.598271,
 0.5338431551728507,
 0.24628457,
 0.5338431551728507,
 0.4653258503903726,
 0.21811514,
 0.24647247512062803,
 0.22101595,
 0.45685704158807683,
 0.6287277,
 0.21032198,
 0.598271,
 0.24628457,
 0.4653258503

In [91]:
for i in range(len(cosine_similirity_scores)):
    data['fit'][i] = cosine_similirity_scores[i]

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [92]:
data.head()

id                                          job_title  \
0   1   C.T. Bauer College of Business Graduate (Magn...   
1   2  Native English Teacher at EPIK (English Progra...   
2   3              Aspiring Human Resources Professional   
3   4             People Development Coordinator at Ryan   
4   5    Advisory Board Member at Celal Bayar University   

                              location connection       fit  
0                       Houston, Texas         85  0.456857  
1                               Kanada        500  0.291101  
2  Raleigh-Durham, North Carolina Area         44  0.628728  
3                        Denton, Texas        500  0.210322  
4                       İzmir, Türkiye        500  0.149897

In [93]:
data.loc[data['fit'] >= 0.4].sort_values(by = 'fit', ascending=False)

id                                          job_title  \
20   21              Aspiring Human Resources Professional   
45   46              Aspiring Human Resources Professional   
32   33              Aspiring Human Resources Professional   
2     3              Aspiring Human Resources Professional   
57   58              Aspiring Human Resources Professional   
96   97              Aspiring Human Resources Professional   
16   17              Aspiring Human Resources Professional   
72   73  Aspiring Human Resources Manager, seeking inte...   
23   24                Aspiring Human Resources Specialist   
59   60                Aspiring Human Resources Specialist   
48   49                Aspiring Human Resources Specialist   
5     6                Aspiring Human Resources Specialist   
35   36                Aspiring Human Resources Specialist   
75   76  Aspiring Human Resources Professional | Passio...   
81   82  Aspiring Human Resources Professional | An ene...   
26   27  Aspiring Human Resources Management student se...   
28   29  Aspiring Human Resources Management student se...   
36   37  Student at Humber College and Aspiring Human R...   
49   50  Student at Humber College and Aspiring Human R...   
38   39  Student at Humber College and Aspiring Human R...   
51   52  Student at Humber College and Aspiring Human R...   
24   25  Student at Humber College and Aspiring Human R...   
8     9  Student at Humber College and Aspiring Human R...   
6     7  Student at Humber College and Aspiring Human R...   
78   79  Liberal Arts Major. Aspiring Human Resources A...   
99  100  Aspiring Human Resources Manager | Graduating ...   
65   66  Experienced Retail Manager and aspiring Human ...   
61   62  Seeking Human Resources HRIS and Generalist Po...   
39   40  Seeking Human Resources HRIS and Generalist Po...   
52   53  Seeking Human Resources HRIS and Generalist Po...   
9    10  Seeking Human Resources HRIS and Generalist Po...   
71   72  Business Management Major and Aspiring Human R...   
56   57   C.T. Bauer College of Business Graduate (Magn...   
43   44   C.T. Bauer College of Business Graduate (Magn...   
30   31   C.T. Bauer College of Business Graduate (Magn...   
18   19   C.T. Bauer College of Business Graduate (Magn...   
14   15   C.T. Bauer College of Business Graduate (Magn...   
13   14   C.T. Bauer College of Business Graduate (Magn...   
0     1   C.T. Bauer College of Business Graduate (Magn...   
29   30              Seeking Human Resources Opportunities   
27   28              Seeking Human Resources Opportunities   
83   84  Human Resources professional for the world lea...   
77   78             Human Resources Generalist at Schwan's   
98   99                   Seeking Human Resources Position   
73   74                       Human Resources Professional   

                               location connection       fit  
20  Raleigh-Durham, North Carolina Area         44  0.628728  
45  Raleigh-Durham, North Carolina Area         44  0.628728  
32  Raleigh-Durham, North Carolina Area         44  0.628728  
2   Raleigh-Durham, North Carolina Area         44  0.628728  
57  Raleigh-Durham, North Carolina Area         44  0.628728  
96                 Kokomo, Indiana Area         71  0.628728  
16  Raleigh-Durham, North Carolina Area         44  0.628728  
72                  Houston, Texas Area          7  0.613567  
23           Greater New York City Area          1  0.598271  
59           Greater New York City Area          1  0.598271  
48           Greater New York City Area          1  0.598271  
5            Greater New York City Area          1  0.598271  
35           Greater New York City Area          1  0.598271  
75                   New York, New York        212  0.597629  
81                   Austin, Texas Area        174  0.577573  
26                  Houston, Texas Area        500  0.576324  
28                  Houston, Texas Area        500  0.576324  
36                

## Ranknet Implementation

In [86]:
from keras import backend
from keras.layers import Activation, Dense, Input, Subtract
from keras.models import Model

In [110]:
#Let's assume the supervisor selects id=27 as the ideal candidate

In [87]:
# Model.
h_1 = Dense(128, activation="relu")
h_2 = Dense(64, activation="relu")
h_3 = Dense(32, activation="relu")
s = Dense(1)

In [99]:
rel_doc = Input(shape=(300,), dtype="float32")

In [100]:
h_1_rel = h_1(rel_doc)
h_2_rel = h_2(h_1_rel)
h_3_rel = h_3(h_2_rel)
rel_score = s(h_3_rel)

In [101]:
irr_doc = Input(shape=(300,), dtype="float32")
h_1_irr = h_1(irr_doc)
h_2_irr = h_2(h_1_irr)
h_3_irr = h_3(h_2_irr)
irr_score = s(h_3_irr)

In [102]:
diff = Subtract()([rel_score, irr_score])

In [103]:
prob = Activation("sigmoid")(diff)

In [104]:
model = Model(inputs=[rel_doc, irr_doc], outputs=prob)
model.compile(optimizer="adadelta", loss="binary_crossentropy")

In [105]:
NUM_EPOCHS = 10
BATCH_SIZE = 2

In [150]:
X = numpy.asarray(jobtitle_embeddings)

In [165]:
#supervisor selects candidate with id=26 as the ideal candidate
data.at[26,'signal'] = 1

In [152]:
y = data['signal']

In [153]:
y = y.to_numpy()

In [154]:
type(X)

numpy.ndarray

In [155]:
X.shape, y.shape

((104, 300), (104,))

In [161]:
#X1 = numpy.asarray(0)

In [162]:
#X1.shape

In [163]:
history = model.fit(X, y, batch_size=BATCH_SIZE, epochs=NUM_EPOCHS, verbose=1)

Epoch 1/10


ValueError: in user code:

    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:754 train_step
        y_pred = self(x, training=True)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:207 assert_input_compatibility
        ' input tensors. Inputs received: ' + str(inputs))

    ValueError: Layer model expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(2, 300) dtype=float32>]
